export const CLASS_NAMES = {
  1: "Warrior",
  2: "Paladin",
  3: "Hunter",
  4: "Rogue",
  5: "Priest",
  6: "Death Knight",
  7: "Shaman",
  8: "Mage",
  9: "Warlock",
  10: "Monk",
  11: "Druid",
  12: "Demon Hunter",
  13: "Evoker",
};

export const RACE_NAMES = {
  1: { name: "Human", faction: "Alliance" },
  2: { name: "Orc", faction: "Horde" },
  3: { name: "Dwarf", faction: "Alliance" },
  4: { name: "Night Elf", faction: "Alliance" },
  5: { name: "Undead (Forsaken)", faction: "Horde" },
  6: { name: "Tauren", faction: "Horde" },
  7: { name: "Gnome", faction: "Alliance" },
  8: { name: "Troll", faction: "Horde" },
  9: { name: "Goblin", faction: "Horde" },
  10: { name: "Blood Elf", faction: "Horde" },
  11: { name: "Draenei", faction: "Alliance" },
  22: { name: "Worgen", faction: "Alliance" },
  25: { name: "Pandaren", faction: "Neutral" },
  26: { name: "Pandaren", faction: "Neutral" },
  27: { name: "Nightborne", faction: "Horde" },
  28: { name: "Highmountain Tauren", faction: "Horde" },
  29: { name: "Void Elf", faction: "Alliance" },
  30: { name: "Lightforged Draenei", faction: "Alliance" },
  31: { name: "Zandalari Troll", faction: "Horde" },
  32: { name: "Kul Tiran", faction: "Alliance" },
  34: { name: "Dark Iron Dwarf", faction: "Alliance" },
  35: { name: "Vulpera", faction: "Horde" },
  36: { name: "Mag'har Orc", faction: "Horde" },
  37: { name: "Mechagnome", faction: "Alliance" },
  52: { name: "Dracthyr", faction: "Neutral" },
};

export const CLASS_COLORS = {
  1: "#C79C6E",
  2: "#F58CBA",
  3: "#ABD473",
  4: "#FFF569",
  5: "#FFFFFF",
  6: "#C41F3B",
  7: "#0070DE",
  8: "#69CCF0",
  9: "#9482C9",
  10: "#00FF96",
  11: "#FF7D0A",
  12: "#A330C9",
  13: "#33937F",
};
